// src/pages/index.jsx
import * as React from 'react'
// import { useEffect } from 'react'
import Navbar from '../components/navbar.jsx'
import About from '../components/about.jsx'
import Projects from '../components/projects.jsx'

import '../styles/pages/index.css'

const IndexPage = () => {

  return (
    <div>
      <main className="custom-container">
        <div className="navbar" id="menu">
          <Navbar />
        </div>
        <div className="contain">
          <section id="about">
            <About />
          </section>
          <section id="projects">
            <Projects />
          </section>
        </div>
      </main>
    </div>
  )
}

export default IndexPage

export const Head = () => <title>O LAB LAC | Portfolio</title>

// pages/index.vue
<template>
  <div>
    <Head>
      <Title>O LAB LAC | Portfolio</Title>
      <Meta name="description" content="My app description" />
    </Head>
    <!-- -->
  </div>
  <div class="custom-container">
    <div class="navbar" id="menu">
      <navbar />
    </div>
    <div class="contain">
      <section id="about">
        <about />
      </section>
      <section id="projects">
        <projects />
      </section>
    </div>
  </div>
</template>

<script>
import { defineComponent } from "vue";
import navbar from "../components/navbar.vue";
import about from "../components/about.vue";
import projects from "../components/projects.vue";

export default defineComponent({
  components: {
    navbar,
    about,
    projects,
  },
});
</script>

<style>
.custom-container {
  overflow: hidden !important;
  overflow-y: scroll !important;
}
</style>
